title: Ajax Knights MD7-White
description: > # this means to ignore newlines until "baseurl:"
  Website to summarize the prizes available during the November 2017 draw
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ajaxknights.online" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2016_style/img/icon-large.png"

social:
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty